# Generated by Django 4.0.3 on 2022-08-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qutation_for_product',
        ),
    ]
